"use server"; import {randomUUID} from "node:crypto"; import {mkdir,unlink,writeFile} from "node:fs/promises"; import path from "node:path"; import {revalidatePath} from "next/cache"; import {redirect} from "next/navigation"; import {prisma} from "@/lib/db"; import {requireAdmin,requireEditor} from "@/lib/admin"; import {slugify} from "@/lib/utils";
const str=(f:FormData,k:string)=>String(f.get(k)??"").trim(),opt=(f:FormData,k:string)=>str(f,k)||null,chk=(f:FormData,k:string)=>f.get(k)==="on",num=(f:FormData,k:string,d=0)=>parseInt(str(f,k)||String(d),10)||d,dt=(f:FormData,k:string)=>{const v=str(f,k);return v?new Date(v):null},links=(f:FormData,k:string)=>f.getAll(k).map(String).filter(Boolean).map(id=>({id})),done=(s:string)=>redirect(`/admin/${s}?saved=1`); function rows(f:FormData,ks:string[]){const c=ks.map(k=>f.getAll(`${k}[]`).map(String)),n=Math.max(0,...c.map(x=>x.length));return Array.from({length:n},(_,i)=>Object.fromEntries(ks.map((k,j)=>[k,c[j][i]?.trim()||""]))).filter(r=>Object.values(r).some(Boolean))}
export async function savePerson(f:FormData){
  await requireEditor();
  const id=str(f,"id"),name=str(f,"name"),areas=links(f,"researchAreaIds");
  if(!name||!str(f,"title")||!str(f,"affiliation"))throw new Error("Required profile fields missing");
  const education=rows(f,["education_degree","education_institution","education_years","education_thesis","education_advisor"]).filter(r=>r.education_degree&&r.education_institution&&r.education_years).map((r,i)=>({degree:r.education_degree,institution:r.education_institution,years:r.education_years,thesis:r.education_thesis||null,advisor:r.education_advisor||null,sortOrder:i}));
  const positions=rows(f,["position_title","position_institution","position_years","position_description"]).filter(r=>r.position_title&&r.position_institution&&r.position_years).map((r,i)=>({title:r.position_title,institution:r.position_institution,years:r.position_years,description:r.position_description||null,sortOrder:i}));
  const talks=rows(f,["talk_title","talk_venue","talk_date","talk_slides"]).filter(r=>r.talk_title&&r.talk_date).map(r=>({title:r.talk_title,venue:r.talk_venue,date:new Date(r.talk_date+"T00:00:00Z"),slidesUrl:r.talk_slides||null}));
  const software=rows(f,["software_name","software_description","software_url","software_languages"]).filter(r=>r.software_name&&r.software_description).map(r=>({name:r.software_name,description:r.software_description,url:r.software_url||null,languages:r.software_languages||null}));
  const awards=rows(f,["award_title","award_issuer","award_year","award_description"]).filter(r=>r.award_title).map((r,i)=>({title:r.award_title,issuer:r.award_issuer||null,year:r.award_year||null,description:r.award_description||null,sortOrder:i}));
  const teaching=rows(f,["teaching_title","teaching_institution","teaching_term","teaching_description"]).filter(r=>r.teaching_title).map((r,i)=>({title:r.teaching_title,institution:r.teaching_institution||null,term:r.teaching_term||null,description:r.teaching_description||null,sortOrder:i}));
  const grants=rows(f,["grant_title","grant_funder","grant_id","grant_role","grant_amount","grant_period","grant_url","grant_description"]).filter(r=>r.grant_title&&r.grant_funder).map((r,i)=>({title:r.grant_title,funder:r.grant_funder,grantId:r.grant_id||null,role:r.grant_role||null,amount:r.grant_amount||null,period:r.grant_period||null,url:r.grant_url||null,description:r.grant_description||null,sortOrder:i}));
  const base={slug:str(f,"slug")||slugify(name),name,role:str(f,"role"),title:str(f,"title"),affiliation:str(f,"affiliation"),email:opt(f,"email"),photo:opt(f,"photo"),bio:opt(f,"bio"),researchSummary:opt(f,"researchSummary"),researchInterests:opt(f,"researchInterests"),website:opt(f,"website"),googleScholar:opt(f,"googleScholar"),inspire:opt(f,"inspire"),orcid:opt(f,"orcid"),arxiv:opt(f,"arxiv"),github:opt(f,"github"),linkedin:opt(f,"linkedin"),cvUrl:opt(f,"cvUrl"),sortOrder:num(f,"sortOrder"),featured:chk(f,"featured"),status:str(f,"status")||"PUBLISHED"};
  if(id)await prisma.person.update({where:{id},data:{...base,researchAreas:{set:areas},education:{deleteMany:{},create:education},positions:{deleteMany:{},create:positions},talks:{deleteMany:{},create:talks},software:{deleteMany:{},create:software},awards:{deleteMany:{},create:awards},teaching:{deleteMany:{},create:teaching},grants:{deleteMany:{},create:grants}}});
  else await prisma.person.create({data:{...base,researchAreas:{connect:areas},education:{create:education},positions:{create:positions},talks:{create:talks},software:{create:software},awards:{create:awards},teaching:{create:teaching},grants:{create:grants}}});
  revalidatePath("/","layout");done("people")
}
export async function saveResearch(f:FormData){await requireEditor();const id=str(f,"id"),title=str(f,"title"),data={slug:str(f,"slug")||slugify(title),title,shortDescription:str(f,"shortDescription"),overview:str(f,"overview"),questions:opt(f,"questions"),methods:opt(f,"methods"),image:opt(f,"image"),sortOrder:num(f,"sortOrder"),featured:chk(f,"featured"),status:str(f,"status")||"PUBLISHED"};if(id)await prisma.researchArea.update({where:{id},data});else await prisma.researchArea.create({data});revalidatePath("/","layout");done("research")}
export async function savePublication(f:FormData){await requireEditor();const id=str(f,"id"),title=str(f,"title"),authors=links(f,"authorIds"),areas=links(f,"researchAreaIds"),projects=links(f,"projectIds"),base={slug:str(f,"slug")||slugify(title),title,authorText:str(f,"authorText"),year:num(f,"year",new Date().getFullYear()),type:str(f,"type")||"PREPRINT",journal:opt(f,"journal"),volume:opt(f,"volume"),pages:opt(f,"pages"),doi:opt(f,"doi"),arxivId:opt(f,"arxivId"),inspireUrl:opt(f,"inspireUrl"),pdfUrl:opt(f,"pdfUrl"),abstract:opt(f,"abstract"),bibtex:opt(f,"bibtex"),featured:chk(f,"featured"),sortOrder:num(f,"sortOrder"),status:str(f,"status")||"PUBLISHED"};if(id)await prisma.publication.update({where:{id},data:{...base,authors:{set:authors},researchAreas:{set:areas},projects:{set:projects}}});else await prisma.publication.create({data:{...base,authors:{connect:authors},researchAreas:{connect:areas},projects:{connect:projects}}});revalidatePath("/","layout");done("publications")}
export async function saveProject(f:FormData){await requireEditor();const id=str(f,"id"),title=str(f,"title"),members=links(f,"memberIds"),areas=links(f,"researchAreaIds"),publications=links(f,"publicationIds"),base={slug:str(f,"slug")||slugify(title),title,shortDescription:str(f,"shortDescription"),description:str(f,"description"),leadText:opt(f,"leadText"),collaborators:opt(f,"collaborators"),startDate:dt(f,"startDate"),endDate:dt(f,"endDate"),status:str(f,"status")||"CURRENT",funding:opt(f,"funding"),githubUrl:opt(f,"githubUrl"),dataUrl:opt(f,"dataUrl"),image:opt(f,"image"),featured:chk(f,"featured"),sortOrder:num(f,"sortOrder"),publishStatus:str(f,"publishStatus")||"PUBLISHED"};if(id)await prisma.project.update({where:{id},data:{...base,members:{set:members},researchAreas:{set:areas},publications:{set:publications}}});else await prisma.project.create({data:{...base,members:{connect:members},researchAreas:{connect:areas},publications:{connect:publications}}});revalidatePath("/","layout");done("projects")}
export async function saveNews(f:FormData){await requireEditor();const id=str(f,"id"),title=str(f,"title"),data={slug:str(f,"slug")||slugify(title),title,summary:str(f,"summary"),body:str(f,"body"),date:dt(f,"date")||new Date(),image:opt(f,"image"),externalUrl:opt(f,"externalUrl"),featured:chk(f,"featured"),sortOrder:num(f,"sortOrder"),status:str(f,"status")||"PUBLISHED"};if(id)await prisma.newsPost.update({where:{id},data});else await prisma.newsPost.create({data});revalidatePath("/","layout");done("news")}
export async function saveEvent(f:FormData){await requireEditor();const id=str(f,"id"),title=str(f,"title"),parse=(k:string)=>{const v=str(f,k);return v?new Date(v+":00+06:00"):null},data={slug:str(f,"slug")||slugify(title),title,speaker:opt(f,"speaker"),affiliation:opt(f,"affiliation"),date:parse("date")||new Date(),endDate:parse("endDate"),timeText:opt(f,"timeText"),location:opt(f,"location"),abstract:opt(f,"abstract"),registrationUrl:opt(f,"registrationUrl"),poster:opt(f,"poster"),status:str(f,"status")||"UPCOMING",publishStatus:str(f,"publishStatus")||"PUBLISHED",sortOrder:num(f,"sortOrder")};if(id)await prisma.event.update({where:{id},data});else await prisma.event.create({data});revalidatePath("/","layout");done("events")}
export async function savePage(f:FormData){await requireEditor();const id=str(f,"id"),title=str(f,"title"),data={slug:str(f,"slug")||slugify(title),title,eyebrow:opt(f,"eyebrow"),body:str(f,"body"),sortOrder:num(f,"sortOrder"),status:str(f,"status")||"PUBLISHED"};if(id)await prisma.page.update({where:{id},data});else await prisma.page.create({data});revalidatePath("/","layout");done("pages")}
export async function saveSettings(f:FormData){await requireAdmin();for(const[k,v]of f.entries())if(typeof v==="string")await prisma.siteSetting.upsert({where:{key:k},update:{value:v.trim()},create:{key:k,value:v.trim()}});revalidatePath("/","layout");done("settings")}
export async function uploadMedia(f:FormData){await requireEditor();const file=f.get("file");if(!(file instanceof File)||!file.size)redirect("/admin/media?error=Choose+a+file");const allowed:Record<string,string>={"image/jpeg":".jpg","image/png":".png","image/webp":".webp","application/pdf":".pdf"};if(!allowed[file.type]||file.size>5*1024*1024)redirect("/admin/media?error=File+type+or+size+not+allowed");const filename=randomUUID()+allowed[file.type],rel=process.env.UPLOAD_DIR||"data/uploads",dir=path.resolve(process.cwd(),rel);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,filename),Buffer.from(await file.arrayBuffer()));await prisma.media.create({data:{filename,originalName:file.name,url:`/uploads/${filename}`,mimeType:file.type,size:file.size,altText:opt(f,"altText")}});done("media")}
export async function deleteEntity(f:FormData){await requireAdmin();const m=str(f,"model"),id=str(f,"id");if(m==="person")await prisma.person.delete({where:{id}});else if(m==="research")await prisma.researchArea.delete({where:{id}});else if(m==="publication")await prisma.publication.delete({where:{id}});else if(m==="project")await prisma.project.delete({where:{id}});else if(m==="news")await prisma.newsPost.delete({where:{id}});else if(m==="event")await prisma.event.delete({where:{id}});else if(m==="page")await prisma.page.delete({where:{id}});else if(m==="media"){const x=await prisma.media.findUnique({where:{id}});if(x){await prisma.media.delete({where:{id}});try{await unlink(path.join(path.resolve(process.cwd(),process.env.UPLOAD_DIR||"data/uploads"),x.filename))}catch{}}}revalidatePath("/","layout");const map:Record<string,string>={person:"people",research:"research",publication:"publications",project:"projects",news:"news",event:"events",page:"pages",media:"media"};done(map[m]||"")}
