import Link from "next/link"; import type {Person,Publication,Project,ResearchArea} from "@prisma/client"; import {humanize,lines} from "@/lib/utils"; import {Portrait} from "@/components/portrait";
export function SectionHeader({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}){return <div className="mb-10 max-w-3xl">{eyebrow&&<div className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-accent">{eyebrow}</div>}<h2 className="section-heading">{title}</h2>{description&&<p className="mt-4 max-w-2xl leading-7 text-muted">{description}</p>}</div>}
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav className="mb-8 text-xs text-muted"><ol className="flex flex-wrap gap-2"><li><Link className="link-academic" href="/">Home</Link></li>{items.map((x,i)=><li key={i} className="flex gap-2"><span>/</span>{x.href?<Link className="link-academic" href={x.href}>{x.label}</Link>:<span>{x.label}</span>}</li>)}</ol></nav>}
export function PersonCard({p}:{p:Person}){return <article className="border-t-2 academic-rule pt-5"><Link href={`/people/${p.slug}`}><div className="relative mb-5 aspect-[4/3] overflow-hidden bg-slate-200"><Portrait slug={p.slug} name={p.name} photo={p.photo} sizes="(max-width:768px) 100vw,33vw"/></div><h3 className="font-serif text-2xl hover:text-accent">{p.name}</h3><p className="mt-1 text-sm font-medium text-navy">{p.title}</p><p className="mt-2 text-xs uppercase tracking-[.12em] text-muted">{humanize(p.role)}</p><p className="mt-4 text-sm leading-6 text-muted">{lines(p.researchInterests).slice(0,3).join(" · ")}</p></Link></article>}
export function PubEntry({p,compact=false}:{p:Publication;compact?:boolean}){return <article className="border-t academic-rule py-6"><div className="grid gap-3 md:grid-cols-[90px_1fr]"><div className="text-sm font-semibold text-muted">{p.year}</div><div><Link href={`/publications/${p.slug}`} className="font-serif text-xl leading-snug hover:text-accent">{p.title}</Link><p className="mt-2 text-sm text-muted">{p.authorText}</p>{!compact&&<div className="mt-3 flex flex-wrap gap-4 text-xs text-muted"><span>{humanize(p.type)}</span>{p.journal&&<span>{p.journal}</span>}{p.arxivId&&<a className="link-academic" href={`https://arxiv.org/abs/${p.arxivId}`}>arXiv:{p.arxivId}</a>}{p.doi&&<a className="link-academic" href={`https://doi.org/${p.doi}`}>DOI</a>}</div>}</div></div></article>}
export function ProjectCard({p}:{p:Project}){return <article className="border-t-2 academic-rule pt-5"><div className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-accent">{humanize(p.status)}</div><Link href={`/projects/${p.slug}`} className="font-serif text-2xl leading-tight hover:text-accent">{p.title}</Link><p className="mt-4 text-sm leading-6 text-muted">{p.shortDescription}</p>{p.leadText&&<p className="mt-4 text-xs text-muted">Lead: {p.leadText}</p>}</article>}
export function AreaCard({a,i}:{a:ResearchArea;i:number}){return <article className="border-t academic-rule py-6"><div className="grid gap-3 md:grid-cols-[64px_1fr]"><div className="font-serif text-2xl text-muted">{String(i+1).padStart(2,"0")}</div><div><Link href={`/research/${a.slug}`} className="font-serif text-2xl hover:text-accent">{a.title}</Link><p className="mt-3 text-sm leading-6 text-muted">{a.shortDescription}</p></div></div></article>}
export function RichText({text}:{text:string}) {
  return <div className="prose-academic">{text.split(/\n\s*\n/).flatMap((block, i) => {
    const [first, ...rest] = block.trim().split("\n");
    if (!first) return [];
    if (first.startsWith("### ")) return [<h3 key={`${i}-h`}>{first.slice(4)}</h3>, ...(rest.length ? [<p key={`${i}-p`}>{rest.join("\n")}</p>] : [])];
    if (first.startsWith("## ")) return [<h2 key={`${i}-h`}>{first.slice(3)}</h2>, ...(rest.length ? [<p key={`${i}-p`}>{rest.join("\n")}</p>] : [])];
    return [<p key={i}>{block}</p>];
  })}</div>;
}
