export const PERSON_ROLES=["PRINCIPAL_INVESTIGATOR","FACULTY","POSTDOC","RESEARCH_ASSISTANT","GRADUATE_STUDENT","UNDERGRADUATE_STUDENT","VISITOR","COLLABORATOR","ALUMNI"] as const;
export const PUBLICATION_TYPES=["JOURNAL_ARTICLE","PREPRINT","CONFERENCE_PROCEEDING","THESIS","BOOK_CHAPTER"] as const;
export const PROJECT_STATUSES=["CURRENT","COMPLETED","PAUSED"] as const;
export const EVENT_STATUSES=["UPCOMING","COMPLETED","CANCELLED"] as const;
export const CONTENT_STATUSES=["DRAFT","PUBLISHED"] as const;
